/**
 * units.js — the reader's script for the WHOLE of Book IX, "The Cyclops":
 * 81 units (76 text + 5 heads), six beats, six leaves (leaf 6 is the closing
 * card), three SETS (shore / cave / sea).
 *
 * GENERATED by tools/ody/emit_units_ody.py from CONTENT-odyssey.md — do not
 * hand-edit the UNITS array; re-emit. Butler's text is verbatim (Gutenberg
 * #1727, public domain), trimmed only with ellipses; CONTENT-odyssey.md is
 * the law (VERBATIM AUDIT 76/76). The reader IS Ulysses telling the tale at
 * Alcinous' court: narration carries no prefix.
 *
 * NAMES ARE THE LEDGER'S (tools/ody/ledger.json):
 *   focus   — ledger LENS names verbatim, per set.
 *   target  — ledger gate targets verbatim (ship / sword / ram-great /
 *             cyclops). Hold gates (G3 bowl, G4 embers) are `hold` verbs.
 *   act     — ledger mark names (fire-ulysses, giant-seat, doorway-seat…),
 *             master/state names (shore-day, cave-dawn, cave-shut,
 *             cave-embers, cave-predawn, sea-dawn), object names
 *             (boulderOpen), gateActs from the ledger (crossing, swordDraw,
 *             slingUnder) + authored verbs the set lane implements
 *             (establish, plate-wineskin, jeer, defy, curse).
 *
 * THE BOOK'S THREE TRAPS:
 *   1. Beats III and IV SHARE LEAF 3 — the collapse chains straight into
 *      THE STAKE with no page turn.
 *   2. Beat VI has NO head unit — heading VI · THE TAUNT rides
 *      ody-vi-01-jeer (BEATS[5] still carries num + title).
 *   3. `cave` is mounted on three leaves (2, 3, 4) in STATE variants —
 *      states are acts (cave-dawn / cave-shut / cave-embers / cave-predawn),
 *      exactly as sherlock units drove room-dim via acts.
 *
 * AMENDMENTS (2026-08-16, verbs/cues are OUR authoring — Butler untouched;
 * recorded in CONTENT-odyssey.md §Amendments):
 *   release — ody-vi-07-myname is the book's one RELEASE verb: press-and-hold
 *             draws the breath (>= 0.6 s), LETTING GO fires the shout and the
 *             story advances on the release frame; soft-fail at 30 s.
 *   rest    — the two big holds (lookhere 1.6 s, embers 3.0 s) carry
 *             rest: true — a released hold KEEPS its progress (no decay, no
 *             reset) and resumes on re-press; their cues say so.
 *   memory  — the defy gate's hesitation (gate-armed -> resolving click) is
 *             remembered by main.js and the closing card's sub gains ONE
 *             clause by the 4 s threshold: END_CARD.subEager / .subHeld.
 *
 * Schema: site-deploy/living/app/units.js (the sherlock original) — same
 * fields, same field order, same exports.
 */

export const UNITS = [
  /* ================= BEAT I · THE TALE BEGUN — SET shore · leaf 1 ================= */

  /* 1.0 — night-shore establishing, night-mist state; the heading chains into the
     voiceover — the court is heard, never seen.
   */
  { id: 'ody-i-00-head', key: 'head1', head: true, num: 'I',
    text: 'The Tale Begun', speaker: '', verb: 'auto', dwell: 3.4,
    focus: 'establishing', page: 1, beat: 1, set: 'shore', clear: true,
    bed: 'shore', act: 'establish' },

  /* 1.1 — voiceover over the dark landfall — fog layer, ship silhouettes ghosting in
     (cut c-night performs beneath).
   */
  { id: 'ody-i-01-bard', key: 'bard',
    text: 'King Alcinous, it is a good thing to hear a bard with such a divine voice as this man has. … Now, however, since you are inclined to ask the story of my sorrows, and rekindle my own sad memories in respect of them, I do not know how to begin, nor yet how to continue and conclude my tale, for the hand of heaven has been laid heavily upon me.',
    speaker: '', verb: 'click', seg: 'landfall', segDur: 8.0, segHold: false,
    focus: 'establishing', page: 1, beat: 1, set: 'shore', clear: true,
    drop: true, sfx: 'keel' },

  /* 1.2 — cameo card, first appearance — the caption plants Beat VI's O.12 echo (cut
     c-firstly); landfall pantomime tail.
   */
  { id: 'ody-i-02-iamulysses', key: 'iamulysses',
    text: 'I am Ulysses son of Laertes, renowned among mankind for all manner of subtlety, so that my fame ascends to heaven. I live in Ithaca…',
    speaker: '', verb: 'click', focus: 'camp-fire', page: 1, beat: 1,
    set: 'shore', clear: true, act: 'fire-ulysses', cameo: 'ulysses',
    cap: 'Ulysses · Son of Laertes · of Ithaca' },

  /* 1.3 — camp embers; bridges the chapter-level Cicons/Lotus-eaters cut.
   */
  { id: 'ody-i-03-troy', key: 'troy',
    text: 'Now, however, I will tell you of the many hazardous adventures which by Jove’s will I met with on my return from Troy.',
    speaker: '', verb: 'click', focus: 'camp-fire', page: 1, beat: 1,
    set: 'shore' },

  /* 1.4 — O.1 text half — the smoke-across-the-strait lift to the mainland lobe; the
     one-eye half stays VISUAL and lands in Beat II.
   */
  { id: 'ody-i-04-lawless', key: 'lawless',
    text: 'We sailed hence, always in much distress, till we came to the land of the lawless and inhuman Cyclopes. … They have no laws nor assemblies of the people, but live in caves on the tops of high mountains; each is lord and master in his family, and they take no account of their neighbours.',
    speaker: '', verb: 'click', focus: 'smoke', page: 1, beat: 1, set: 'shore',
    clear: true, fact: 'O.1' },

  /* 1.5 — shore day state — goats scattering; the hunt is pantomime after the line (cut
     c-hunt).
   */
  { id: 'ody-i-05-dawn', key: 'dawn1',
    text: 'When the child of morning, rosy-fingered Dawn appeared, we admired the island and wandered all over it, while the nymphs Jove’s daughters roused the wild goats that we might get some meat for our dinner.',
    speaker: '', verb: 'click', seg: 'hunt', segDur: 5.0, segHold: false,
    focus: 'establishing', page: 1, beat: 1, set: 'shore', clear: true,
    sfx: 'goats', act: 'shore-day' },

  /* 1.6 — beach feast, all eyes to the strait — stubble-fire smoke plainly seen (O.1
     reinforcement); sun-down time-lapse; the crew gathers to the council marks.
   */
  { id: 'ody-i-06-smoke', key: 'smoke',
    text: 'While we were feasting we kept turning our eyes towards the land of the Cyclopes, which was hard by, and saw the smoke of their stubble fires. We could almost fancy we heard their voices and the bleating of their sheep and goats, but when the sun went down and it came on dark, we camped down upon the beach, and next morning I called a council.',
    speaker: '', verb: 'click', focus: 'establishing', page: 1, beat: 1,
    set: 'shore', clear: true, sfx: 'bleats', act: 'council-ulysses' },

  /* 1.7 — GATE G1 — the beached ship (ship-2 hull centre per the ledger); gateAct
     crossing performs the embarkation and the strait (cut c-board).
   */
  { id: 'ody-i-07-council', key: 'council',
    text: '"Stay here, my brave fellows… all the rest of you, while I go with my ship and exploit these people myself: I want to see if they are uncivilised savages, or a hospitable and humane race."',
    speaker: 'ULYSSES', verb: 'target', target: 'ship', gateAct: 'crossing',
    gateSfx: 'oars', cue: 'click the ship · cross to the mainland',
    focus: 'council', page: 1, beat: 1, set: 'shore', clear: true },

  /* 1.8 — mainland approach — slow push onto the laurel mouth (lens cavemouth-push-from
     animates to -to).
   */
  { id: 'ody-i-08-cave', key: 'cave',
    text: 'When we got to the land, which was not far, there, on the face of a cliff near the sea, we saw a great cave overhung with laurels.',
    speaker: '', verb: 'click', focus: 'cavemouth-push-to', page: 1, beat: 1,
    set: 'shore', clear: true, sfx: 'wind', act: 'entry-mainland' },

  /* 1.9 — the mouth holds EMPTY (he is away); on the crag simile the lens tilts to the
     bare cliff-top — Beat VI pre-echo.
   */
  { id: 'ody-i-09-monster', key: 'monster',
    text: 'This was the abode of a huge monster who was then away from home shepherding his flocks. He would have nothing to do with other people, but led the life of an outlaw. He was a horrid creature, not like a human being at all, but resembling rather some crag that stands out boldly against the sky on the top of a high mountain.',
    speaker: '', verb: 'click', focus: 'crag-tilt', page: 1, beat: 1,
    set: 'shore' },

  /* 1.10 — the twelve chosen, the rest stay; Ulysses shoulders the dark goatskin.
   */
  { id: 'ody-i-10-wineskin', key: 'wineskin',
    text: 'I told my men to draw the ship ashore, and stay where they were, all but the twelve best among them, who were to go along with myself. I also took a goatskin of sweet black wine which had been given me by Maron, son of Euanthes, who was priest of Apollo the patron god of Ismarus, and lived within the wooded precincts of the temple.',
    speaker: '', verb: 'click', focus: 'ship-mid', page: 1, beat: 1,
    set: 'shore', clear: true, sfx: 'slosh', act: 'twelve-at-ship' },

  /* 1.11 — O.2 strength detail — the skin close IN-WORLD, not the inset yet.
   */
  { id: 'ody-i-11-twentyone', key: 'twentyone',
    text: '…when he drank it he mixed twenty parts of water to one of wine, and yet the fragrance from the mixing-bowl was so exquisite that it was impossible to refrain from drinking.',
    speaker: '', verb: 'click', focus: 'skin-close', page: 1, beat: 1,
    set: 'shore' },

  /* 1.12 — O.2 LANDS — the chapter's ONLY inset rises; the party climbs behind the plate
     (mark climb-path); the completing click drops the plate and turns leaf 1 to 2.
   */
  { id: 'ody-i-12-misgave', key: 'misgave',
    text: 'I filled a large skin with this wine, and took a wallet full of provisions with me, for my mind misgave me that I might have to deal with some savage who would be of great strength, and would respect neither right nor law.',
    speaker: '', verb: 'click', endsBeat: true, focus: 'cavemouth-push-to',
    page: 1, beat: 1, set: 'shore', clear: true, act: 'plate-wineskin',
    fact: 'O.2' },

  /* ================= BEAT II · THE CAVE — SET cave · leaf 2 ================= */

  /* 2.0 — boulder-open day state (cave-dawn master); the men slip in past the empty pens
     under the heading (K1).
   */
  { id: 'ody-ii-00-head', key: 'head2', head: true, num: 'II',
    text: 'The Cave', speaker: '', verb: 'click', seg: 'entry', segDur: 5.0,
    segHold: true, focus: 'establishing', page: 2, beat: 2, set: 'cave',
    clear: true, bed: 'cave', act: 'cave-dawn' },

  /* 2.1 — lens sweeps racks + ranked pens (K2); the laden-men tableau, heads jerked
     seaward (K3).
   */
  { id: 'ody-ii-01-beg', key: 'beg',
    text: 'His cheese-racks were loaded with cheeses, and he had more lambs and kids than his pens could hold… When they saw all this, my men begged me to let them first steal some cheeses, and make off with them to the ship…',
    speaker: '', verb: 'click', focus: 'racks-sweep', page: 2, beat: 2,
    set: 'cave', clear: true, sfx: 'bleats', act: 'cheese-rack', fact: 'O.3a' },

  /* 2.2 — the chapter's tragic hinge — the waiting segment plays on advance (K4).
   */
  { id: 'ody-ii-02-present', key: 'present',
    text: 'It would have been indeed better if we had done so but I would not listen to them, for I wanted to see the owner himself, in the hope that he might give me a present. When, however, we saw him my poor men found him ill to deal with.',
    speaker: '', verb: 'click', focus: 'doorlight-hinge', page: 2, beat: 2,
    set: 'cave', fact: 'O.3b' },

  /* 2.3 — POLYPHEMUS enters under the firewood load; single-eye cameo art carries O.1's
     visual half; the men scatter to the far dark (K5).
   */
  { id: 'ody-ii-03-return', key: 'return2',
    text: 'When he came, he brought in with him a huge load of dry firewood to light the fire for his supper, and this he flung with such a noise on to the floor of his cave that we hid ourselves for fear at the far end of the cavern.',
    speaker: '', verb: 'click', seg: 'return', segDur: 7.0, segHold: true,
    focus: 'discovery-low', page: 2, beat: 2, set: 'cave', clear: true,
    sfx: 'crash', act: 'huddle-far', cameo: 'polyphemus',
    cap: 'Polyphemus · the Cyclops' },

  /* 2.4 — the boulder-shut pantomime precedes the text (K6) — a state swap under the
     grind-boom; the waggons measure lands while the stone settles.
   */
  { id: 'ody-ii-04-boulder', key: 'boulder',
    text: '…so huge that two and twenty strong four-wheeled waggons would not be enough to draw it from its place against the doorway.',
    speaker: '', verb: 'click', focus: 'mouth', page: 2, beat: 2, set: 'cave',
    clear: true, sfx: 'boulder', act: 'cave-shut', fact: 'O.4' },

  /* 2.5 — milking/curdling compresses on entry (K7/K8, the supper bowl planted); the
     fire flares, the head turns — FIRST close lens on the single eye (O.1 visual).
   */
  { id: 'ody-ii-05-strangers', key: 'strangers',
    text: 'Strangers, who are you? Where do sail from? Are you traders, or do you sail the sea as rovers, with your hands against every man, and every man’s hand against you?',
    speaker: 'POLYPHEMUS', verb: 'click', seg: 'milking', segDur: 4.0,
    segHold: true, focus: 'eye-close', page: 2, beat: 2, set: 'cave',
    clear: true, sfx: 'boom', act: 'giant-seat' },

  /* 2.6 — arms wide, firelight between the small figure and the seated bulk; no cue.
   */
  { id: 'ody-ii-06-plea', key: 'plea',
    text: 'We are Achaeans on our way home from Troy… We therefore humbly pray you to show us some hospitality… for we are your suppliants, and Jove takes all respectable travellers under his protection, for he is the avenger of all suppliants and foreigners in distress.',
    speaker: 'ULYSSES', verb: 'click', focus: 'twoshot', page: 2, beat: 2,
    set: 'cave', clear: true, act: 'suppliant' },

  /* 2.7 — the pitiless answer, delivered flat — he never stops working.
   */
  { id: 'ody-ii-07-pitiless', key: 'pitiless',
    text: 'Stranger… We Cyclopes do not care about Jove or any of your blessed gods, for we are ever so much stronger than they. I shall not spare either yourself or your companions out of any regard for Jove, unless I am in the humour for doing so.',
    speaker: 'POLYPHEMUS', verb: 'click', focus: 'twoshot', page: 2, beat: 2,
    set: 'cave' },

  /* 2.8 — the probe made visible (K12a): the giant leans in toward the mouth.
   */
  { id: 'ody-ii-08-shipfast', key: 'shipfast',
    text: 'And now tell me where you made your ship fast when you came on shore. Was it round the point, or is she lying straight off the land?',
    speaker: 'POLYPHEMUS', verb: 'click', focus: 'twoshot', page: 2, beat: 2,
    set: 'cave' },

  /* 2.9 — the lie performed as theatre (K12b) — the reader beached that ship in Beat I's
     own crossing.
   */
  { id: 'ody-ii-09-shiplie', key: 'shiplie',
    text: 'Neptune… sent my ship on to the rocks at the far end of your country, and wrecked it. We were driven on to them from the open sea, but I and those who are with me escaped the jaws of death.',
    speaker: 'ULYSSES', verb: 'click', focus: 'twoshot', page: 2, beat: 2,
    set: 'cave', clear: true },

  /* 2.10 — the two-at-a-clutch seize IN SHADOW (K13) — seg seize restages IDENTICALLY at
     Beat III's two meals (O.6's carrier); then the sprawl among the sheep,
     snore-bed, fire to low glow (K14).
   */
  { id: 'ody-ii-10-firstmeal', key: 'firstmeal',
    text: 'The cruel wretch vouchsafed me not one word of answer… Then he tore them limb from limb and supped upon them. He gobbled them up like a lion in the wilderness…',
    speaker: '', verb: 'click', seg: 'seize', segDur: 6.0, segHold: true,
    focus: 'meal-close', page: 2, beat: 2, set: 'cave', clear: true,
    sfx: 'seize', act: 'cave-embers', fact: 'O.6' },

  /* 2.11 — GATE G2 — the glint at the hip; the reader performs the fatal instinct so the
     text can refuse it (O.5 setup).
   */
  { id: 'ody-ii-11-sword', key: 'sword',
    text: 'I was at first inclined to seize my sword, draw it, and drive it into his vitals…',
    speaker: '', verb: 'target', target: 'sword', gateAct: 'swordDraw',
    gateSfx: 'sword', cue: 'click the sword · do what instinct asks',
    focus: 'sword', page: 2, beat: 2, set: 'cave', clear: true,
    act: 'sword-ulysses' },

  /* 2.12 — the blade STOPS mid-air; the pan lands on the boulder filling the mouth; steel
     sheathed unheard — O.5 lands.
   */
  { id: 'ody-ii-12-shiftstone', key: 'shiftstone',
    text: '…but I reflected that if I did we should all certainly be lost, for we should never be able to shift the stone which the monster had put in front of the door.',
    speaker: '', verb: 'click', focus: 'sword', page: 2, beat: 2, set: 'cave',
    fact: 'O.5' },

  /* 2.13 — widest lens of the beat: twelve small shapes against the stone; the click
     turns the page to leaf 3.
   */
  { id: 'ody-ii-13-tillmorning', key: 'tillmorning',
    text: 'So we stayed sobbing and sighing where we were till morning came.',
    speaker: '', verb: 'click', endsBeat: true, focus: 'establishing', page: 2,
    beat: 2, set: 'cave', clear: true, sfx: 'sob' },

  /* ================= BEAT III · NOBODY — SET cave · leaf 3 (SHARED with Beat IV) ================= */

  /* 3.0 — leaf 3 mounts on the 2-to-3 turn; dawn light through the mouth-chinks, embers
     grey, the giant asleep among the flock.
   */
  { id: 'ody-iii-00-head', key: 'head3', head: true, num: 'III',
    text: 'Nobody', speaker: '', verb: 'click', focus: 'establishing', page: 3,
    beat: 3, set: 'cave', clear: true, bed: 'cave', act: 'cave-predawn' },

  /* 3.1 — dawn routine in pantomime under the ellipsis (c1); seg seize restaged
     IDENTICALLY — men now eight.
   */
  { id: 'ody-iii-01-morningmeal', key: 'morningmeal',
    text: 'When the child of morning, rosy-fingered dawn, appeared, he again lit his fire… he clutched up two more of my men, and began eating them for his morning’s meal.',
    speaker: '', verb: 'click', seg: 'seize', segDur: 6.0, segHold: true,
    focus: 'meal-close', page: 3, beat: 3, set: 'cave', clear: true,
    sfx: 'seize', act: 'milking', fact: 'O.6' },

  /* 3.2 — stone-lift + flock-stream precede the text (c2); the simile lands AS the stone
     claps to and the light dies.
   */
  { id: 'ody-iii-02-quiverlid', key: 'quiverlid',
    text: '…he at once put it back again—as easily as though he were merely clapping the lid on to a quiver full of arrows.',
    speaker: '', verb: 'click', seg: 'flock-out', segDur: 5.0, segHold: true,
    focus: 'mouth', page: 3, beat: 3, set: 'cave', clear: true, sfx: 'boulder' },

  /* 3.3 — sealed dim; the muffled Shoo, shoo and fading flock-bells through the stone
     (c3); push-in on Ulysses alone among the pens.
   */
  { id: 'ody-iii-03-scheme', key: 'scheme',
    text: '…so I was left to scheme some way of taking my revenge and covering myself with glory.',
    speaker: '', verb: 'click', focus: 'scheme-push', page: 3, beat: 3,
    set: 'cave', clear: true, sfx: 'shoo', act: 'scheme' },

  /* 3.4 — the searching pan finds the club; mast-scale delivered VISUALLY — figures tiny
     beside it; cut/fine/point/char montage under the ellipses.
   */
  { id: 'ody-iii-04-club', key: 'club',
    text: 'The Cyclops had a great club which was lying near one of the sheep pens; it was of green olive wood… I went up to this club and cut off about six feet of it… lastly I brought it to a point myself, charring the end in the fire to make it harder.',
    speaker: '', verb: 'click', seg: 'stake-make', segDur: 6.0, segHold: true,
    focus: 'club-wide', page: 3, beat: 3, set: 'cave', clear: true,
    sfx: 'chop' },

  /* 3.5 — the stake slides under the painted dung-litter (c8); shaken helmet, four step
     forward, Ulysses the fifth.
   */
  { id: 'ody-iii-05-lots', key: 'lots',
    text: 'When I had done this I hid it under dung… and told the men to cast lots which of them should venture along with myself to lift it and bore it into the monster’s eye while he was asleep. The lot fell upon the very four whom I should have chosen, and I myself made five.',
    speaker: '', verb: 'click', focus: 'lots-overhead', page: 3, beat: 3,
    set: 'cave', sfx: 'lots', act: 'stake-hide' },

  /* 3.6 — evening return — the WHOLE flock pours in, pens visibly overfull; the anomaly
     pays off in Beat V.
   */
  { id: 'ody-iii-06-return', key: 'return3',
    text: 'In the evening the wretch came back from shepherding, and drove his flocks into the cave—this time driving them all inside, and not leaving any in the yards; I suppose some fancy must have taken him, or a god must have prompted him to do so.',
    speaker: '', verb: 'click', seg: 'flock-in', segDur: 6.0, segHold: true,
    focus: 'establishing', page: 3, beat: 3, set: 'cave', clear: true,
    sfx: 'flock' },

  /* 3.7 — boulder re-seated + milking repeated (c9); seg seize IDENTICAL a third time —
     men now six; the ivy bowl becomes the hot object.
   */
  { id: 'ody-iii-07-suppertwo', key: 'suppertwo',
    text: '…he gripped up two more of my men, and made his supper off them. So I went up to him with an ivy-wood bowl of black wine in my hands:',
    speaker: '', verb: 'click', seg: 'seize', segDur: 6.0, segHold: true,
    focus: 'meal-close', page: 3, beat: 3, set: 'cave', clear: true,
    sfx: 'seize', act: 'cave-shut', fact: 'O.6' },

  /* 3.8 — GATE G3 — the bowl fills with the hold (pour 1; the set pantomimes pours 2-3
     under the two autos that follow, ledger holds:3); his drain-and-thrust-back IS
     the begging (c10).
   */
  { id: 'ody-iii-08-lookhere', key: 'lookhere',
    text: 'Look here, Cyclops… you have been eating a great deal of man’s flesh, so take this and drink some wine, that you may see what kind of liquor we had on board my ship…',
    speaker: 'ULYSSES', verb: 'hold',
    cue: 'hold the bowl · fill it — and again — and again — rest is allowed',
    hold: 1.6, rest: true, focus: 'bowl-close', page: 3, beat: 3, set: 'cave',
    clear: true, sfx: 'pour', act: 'bowl-offer' },

  /* 3.9 — lands on pour-1 release; the flushed face leans down, the one eye glittering;
     "tell me your name" baits O.8's trap.
   */
  { id: 'ody-iii-09-besokind', key: 'besokind',
    text: 'Be so kind… as to give me some more, and tell me your name at once. I want to make you a present that you will be glad to have. We have wine even in this country, for our soil grows grapes and the sun ripens them, but this drinks like Nectar and Ambrosia all in one.',
    speaker: 'POLYPHEMUS', verb: 'auto', dwell: 9.0, focus: 'face-flush',
    page: 3, beat: 3, set: 'cave' },

  /* 3.10 — lands with pour-3 — O.7: three fills, three heedless drains; the giant sways,
     the fire sinks toward embers.
   */
  { id: 'ody-iii-10-thrice', key: 'thrice',
    text: 'I then gave him some more; three times did I fill the bowl for him, and three times did he drain it without thought or heed; then, when I saw that the wine had got into his head, I said to him as plausibly as I could:',
    speaker: '', verb: 'auto', dwell: 8.0, focus: 'bowl-close', page: 3,
    beat: 3, set: 'cave', clear: true, fact: 'O.7' },

  /* 3.11 — the pun — half-bow at "plausibly"; near-silence under the line.
   */
  { id: 'ody-iii-11-noman', key: 'noman',
    text: 'Cyclops, you ask my name and I will tell it you; give me, therefore, the present you promised me; my name is Noman; this is what my father and mother and my friends have always called me.',
    speaker: 'ULYSSES', verb: 'click', focus: 'twoshot', page: 3, beat: 3,
    set: 'cave', clear: true, fact: 'O.8a' },

  /* 3.12 — the price, adjacent to the pun; the empty bowl loose in his fingers; this
     click fires the collapse.
   */
  { id: 'ody-iii-12-nomanlast', key: 'nomanlast',
    text: 'Then I will eat all Noman’s comrades before Noman himself, and will keep Noman for the last. This is the present that I will make him.',
    speaker: 'POLYPHEMUS', verb: 'click', focus: 'twoshot', page: 3, beat: 3,
    set: 'cave', fact: 'O.8b' },

  /* 3.13 — rides the collapse segment (~6 s); the sick-turn in shadow, sound-led; Beat
     IV's heading lands on this SAME leaf — NO page turn.
   */
  { id: 'ody-iii-13-neck', key: 'neck',
    text: 'His great neck hung heavily backwards and a deep sleep took hold upon him.',
    speaker: '', verb: 'auto', dwell: 6.5, seg: 'collapse', segDur: 6.0,
    segHold: true, focus: 'establishing', page: 3, beat: 3, set: 'cave',
    clear: true, sfx: 'fall', act: 'cave-embers' },

  /* ================= BEAT IV · THE STAKE — SET cave · leaf 3 (no turn in; turns out 3→4) ================= */

  /* 4.0 — NO page turn — the heading lands on leaf 3 already mounted, dark-embers state,
     the giant sprawled by the pens.
   */
  { id: 'ody-iv-00-head', key: 'head4', head: true, num: 'IV',
    text: 'The Stake', speaker: '', verb: 'auto', dwell: 3.4,
    focus: 'establishing', page: 3, beat: 4, set: 'cave', clear: true },

  /* 4.1 — GATE G4 — glow rides the hold (watermark law); at full heat the drive fires
     itself; the blinding clock (~14 s) zeroes on resolve.
   */
  { id: 'ody-iv-01-embers', key: 'embers',
    text: '"Then I thrust the beam of wood far into the embers to heat it, and encouraged my men lest any of them should turn faint-hearted."',
    speaker: '', verb: 'hold',
    cue: 'hold the stake in the embers · until it glows — rest is allowed',
    hold: 3.0, rest: true, focus: 'ember-close', page: 3, beat: 4, set: 'cave',
    clear: true, sfx: 'embers' },

  /* 4.2 — fires on gate completion and starts the blinding clock; the drawn point lights
     five faces from below; margin cleared for the twist.
   */
  { id: 'ody-iv-02-glowing', key: 'glowing',
    text: '"When the wood, green though it was, was about to blaze, I drew it out of the fire glowing with heat, and my men gathered round me, for heaven had filled their hearts with courage."',
    speaker: '', verb: 'auto', dwell: 3.6, focus: 'ember-close', page: 3,
    beat: 4, set: 'cave', clear: true },

  /* 4.3 — the drive itself is PANTOMIME (cut #6); the auger simile lands ON the twist —
     O.9.
   */
  { id: 'ody-iv-03-auger', key: 'auger',
    text: '"…I kept turning it round and round as though I were boring a hole in a ship’s plank with an auger, which two men with a wheel and strap can keep on turning as long as they choose."',
    speaker: '', verb: 'clock', at: 4.2, focus: 'drive-tight', page: 3,
    beat: 4, set: 'cave', clear: true, sfx: 'grind', fact: 'O.9' },

  /* 4.4 — steam plumes up the firelight shaft; horror staged in shadow, not lingered.
   */
  { id: 'ody-iv-04-bore', key: 'bore',
    text: '"Even thus did we bore the red hot beam into his eye, till the boiling blood bubbled all over it as we worked it round and round, so that the steam from the burning eyeball scalded his eyelids and eyebrows, and the roots of the eye sputtered in the fire."',
    speaker: '', verb: 'clock', at: 7.4, focus: 'drive-tight', page: 3,
    beat: 4, set: 'cave', sfx: 'sputter' },

  /* 4.5 — the HISS then the YELL — camera shake, roof-dust, the flocks surging in the
     pens.
   */
  { id: 'ody-iv-05-hiss', key: 'hiss',
    text: '"As a blacksmith plunges an axe or hatchet into cold water to temper it—for it is this that gives strength to the iron—and it makes a great hiss as he does so, even thus did the Cyclops’ eye hiss round the beam of olive wood, and his hideous yells made the cave ring again."',
    speaker: '', verb: 'clock', at: 10.4, focus: 'drive-tight', page: 3,
    beat: 4, set: 'cave', sfx: 'hiss' },

  /* 4.6 — pluck-and-hurl pantomime inside the ellipsis (cut #7); lamplight gathers
     through the boulder seams; click pacing resumes next unit.
   */
  { id: 'ody-iv-06-fright', key: 'fright',
    text: '"We ran away in a fright… shouting as he did so to the other Cyclopes who lived on the bleak headlands near him; so they gathered from all quarters round his cave when they heard him crying, and asked what was the matter with him."',
    speaker: '', verb: 'clock', at: 12.6, focus: 'mouth', page: 3, beat: 4,
    set: 'cave', clear: true, sfx: 'clatter' },

  /* 4.7 — voices from BEYOND the stone — voice-only card, first appearance; O.10 opens.
   */
  { id: 'ody-iv-07-whatails', key: 'whatails',
    text: '"What ails you, Polyphemus… that you make such a noise, breaking the stillness of the night, and preventing us from being able to sleep? Surely no man is carrying off your sheep? Surely no man is trying to kill you either by fraud or by force?"',
    speaker: 'A CYCLOPS', verb: 'click', focus: 'mouth', page: 3, beat: 4,
    set: 'cave', clear: true, cameo: 'a-cyclops',
    cap: 'A Cyclops · the Neighbours' },

  /* 4.8 — the pun lands — a held beat of silence outside.
   */
  { id: 'ody-iv-08-nomankilling', key: 'nomankilling',
    text: '"Noman is killing me by fraud; no man is killing me by force."',
    speaker: 'POLYPHEMUS', verb: 'click', focus: 'mouth', page: 3, beat: 4,
    set: 'cave', fact: 'O.10a' },

  /* 4.9 — O.13a PLANTED — "pray to your father Neptune", said plainly through the stone.
   */
  { id: 'ody-iv-09-mustbeill', key: 'mustbeill',
    text: '"Then… if no man is attacking you, you must be ill; when Jove makes people ill, there is no help for it, and you had better pray to your father Neptune."',
    speaker: 'A CYCLOPS', verb: 'click', focus: 'mouth', page: 3, beat: 4,
    set: 'cave', fact: 'O.13a' },

  /* 4.10 — the lamps RECEDE — the seams dim one by one; O.10 completes: they GO.
   */
  { id: 'ody-iv-10-wentaway', key: 'wentaway',
    text: '"Then they went away, and I laughed inwardly at the success of my clever stratagem…"',
    speaker: '', verb: 'click', focus: 'mouth', page: 3, beat: 4, set: 'cave',
    clear: true, sfx: 'footfalls', cameo: null, fact: 'O.10b' },

  /* 4.11 — the blind grope along the wall; the stone drawn aside — night air spills in
     (the Beat II shut-sfx reversed).
   */
  { id: 'ody-iv-11-stone', key: 'stone',
    text: '"…but the Cyclops, groaning and in an agony of pain, felt about with his hands till he found the stone and took it from the door;"',
    speaker: '', verb: 'click', focus: 'mouth', page: 3, beat: 4, set: 'cave',
    sfx: 'boulder', act: 'boulderOpen' },

  /* 4.12 — the closing tableau — seated in the mouth, hands spread; the door open and
     utterly barred; the click turns leaf 3 to 4.
   */
  { id: 'ody-iv-12-doorway', key: 'doorway',
    text: '"…then he sat in the doorway and stretched his hands in front of it to catch anyone going out with the sheep, for he thought I might be foolish enough to attempt this."',
    speaker: '', verb: 'click', endsBeat: true, focus: 'mouth', page: 3,
    beat: 4, set: 'cave', clear: true, act: 'doorway-seat' },

  /* ================= BEAT V · THE RAMS — SET cave, dawn state · leaf 4 ================= */

  /* 5.0 — leaf 4 mounts, pre-dawn dark; the giant seated filling the doorway (mark
     doorway-seat); six crew huddled by the pens.
   */
  { id: 'ody-v-00-head', key: 'head5', head: true, num: 'V', text: 'The Rams',
    speaker: '', verb: 'auto', dwell: 3.4, focus: 'establishing', page: 4,
    beat: 5, set: 'cave', clear: true, bed: 'cave', act: 'cave-predawn' },

  /* 5.1 — slow pull from the blocked mouth to Ulysses' face; the seated giant stays in
     frame — the problem IS the doorway.
   */
  { id: 'ody-v-01-puzzling', key: 'puzzling',
    text: 'As for myself I kept on puzzling to think how I could best save my own life and those of my companions; I schemed and schemed, as one who knows that his life depends upon it, for the danger was very great.',
    speaker: '', verb: 'click', focus: 'establishing', page: 4, beat: 5,
    set: 'cave', clear: true },

  /* 5.2 — withies from the sleeping-litter; ram-trios lashed noiselessly UNDER the
     giant's breathing.
   */
  { id: 'ody-v-02-withies', key: 'withies',
    text: 'In the end I deemed that this plan would be the best; the male sheep were well grown, and carried a heavy black fleece, so I bound them noiselessly in threes together, with some of the withies on which the wicked monster used to sleep.',
    speaker: '', verb: 'click', seg: 'lash-trios', segDur: 5.0, segHold: false,
    focus: 'meal-close', page: 4, beat: 5, set: 'cave', clear: true,
    sfx: 'withies' },

  /* 5.3 — first man slides under the middle ram; the flanks close over him; five more
     trios stagger in, lens low at sheep height.
   */
  { id: 'ody-v-03-threetoaman', key: 'threetoaman',
    text: 'There was to be a man under the middle sheep, and the two on either side were to cover him, so that there were three sheep to each man.',
    speaker: '', verb: 'click', focus: 'meal-close', page: 4, beat: 5,
    set: 'cave' },

  /* 5.4 — GATE G5 — the great ram apart at the rail; the click IS the sling-under, the
     chapter's no-text moment (cut C1).
   */
  { id: 'ody-v-04-greatram', key: 'greatram',
    text: 'As for myself there was a ram finer than any of the others…',
    speaker: '', verb: 'target', target: 'ram-great', gateAct: 'slingUnder',
    gateSfx: 'wool', cue: 'click the great ram · go last, beneath him',
    focus: 'ram-close', page: 4, beat: 5, set: 'cave', clear: true,
    act: 'ram-stand' },

  /* 5.5 — dawn-shaft breaks past the seated giant; the flock streams toward the light;
     the ewes stay bleating.
   */
  { id: 'ody-v-05-dawn', key: 'dawn5',
    text: 'Thus, then, did we wait in great fear of mind till morning came, but when the child of morning, rosy-fingered Dawn, appeared, the male sheep hurried out to feed, while the ewes remained bleating about the pens waiting to be milked, for their udders were full to bursting…',
    speaker: '', verb: 'click', focus: 'establishing', page: 4, beat: 5,
    set: 'cave', clear: true, sfx: 'flock', act: 'cave-dawn' },

  /* 5.6 — the hand-pass — O.11's core image: the huge palm strokes the very fleece that
     hides a man.
   */
  { id: 'ody-v-06-feltbacks', key: 'feltbacks',
    text: '…but their master in spite of all his pain felt the backs of all the sheep as they stood upright, without being sharp enough to find out that the men were underneath their bellies.',
    speaker: '', verb: 'click', focus: 'handpass-tight', page: 4, beat: 5,
    set: 'cave', clear: true, sfx: 'wool', fact: 'O.11' },

  /* 5.7 — the great ram HALTED under the palm in the doorway; the stage empties around
     the held pair.
   */
  { id: 'ody-v-07-lastofall', key: 'lastofall',
    text: 'As the ram was going out, last of all, heavy with its fleece and with the weight of my crafty self, Polyphemus laid hold of it and said:',
    speaker: '', verb: 'click', focus: 'doorway-twoshot', page: 4, beat: 5,
    set: 'cave', clear: true, act: 'ram-at-mouth' },

  /* 5.8 — gentle for the first time in the chapter; Ulysses' fists in the fleece in the
     lower frame.
   */
  { id: 'ody-v-08-ramspeech1', key: 'ramspeech1',
    text: '"My good ram, what is it that makes you the last to leave my cave this morning? You are not wont to let the ewes go before you, but lead the mob with a run whether to flowery mead or bubbling fountain, and are the first to come home again at night; but now you lag last of all."',
    speaker: 'POLYPHEMUS', verb: 'click', focus: 'doorway-twoshot', page: 4,
    beat: 5, set: 'cave', clear: true },

  /* 5.9 — the hand tightens at "I will have his life yet" — the life he wants hangs an
     arm's length under it.
   */
  { id: 'ody-v-09-ramspeech2', key: 'ramspeech2',
    text: '"Is it because you know your master has lost his eye, and are sorry because that wicked Noman and his horrid crew has got him down in his drink and blinded him? But I will have his life yet."',
    speaker: 'POLYPHEMUS', verb: 'click', focus: 'doorway-twoshot', page: 4,
    beat: 5, set: 'cave' },

  /* 5.10 — the blind head turns back into the cave; then the palm lifts.
   */
  { id: 'ody-v-10-ramspeech3', key: 'ramspeech3',
    text: '"If you could understand and talk, you would tell me where the wretch is hiding, and I would dash his brains upon the ground till they flew all over the cave. I should thus have some satisfaction for the harm this no-good Noman has done me."',
    speaker: 'POLYPHEMUS', verb: 'click', focus: 'doorway-twoshot', page: 4,
    beat: 5, set: 'cave' },

  /* 5.11 — the ram trots clear; Ulysses drops from beneath and cuts each man free; the
     giant still seated, small now.
   */
  { id: 'ody-v-11-freed', key: 'freed',
    text: 'As he spoke he drove the ram outside, but when we were a little way out from the cave and yards, I first got from under the ram’s belly, and then freed my comrades…',
    speaker: '', verb: 'click', seg: 'free-men', segDur: 6.0, segHold: false,
    focus: 'freed-overshoulder', page: 4, beat: 5, set: 'cave', clear: true,
    sfx: 'withies' },

  /* 5.12 — the completing click turns leaf 4 to 5; seg run-to-ship plays across the turn
     (cut C2) — the nod-and-frown hush is its face beat.
   */
  { id: 'ody-v-12-aboard', key: 'aboard',
    text: '…and told them to get all the sheep on board at once and put out to sea; so they went aboard, took their places, and smote the grey sea with their oars.',
    speaker: '', verb: 'click', endsBeat: true, focus: 'freed-overshoulder',
    page: 4, beat: 5, set: 'cave', clear: true, sfx: 'oars' },

  /* ================= BEAT VI · THE TAUNT — SET sea · leaf 5 (NO head unit; → closing card) ================= */

  /* 6.1 — GATE G6, first resolution; the sea SET mounts under heading VI · THE TAUNT —
     NO head unit, the heading rides this unit; two-plane wide.
   */
  { id: 'ody-vi-01-jeer', key: 'jeer',
    text: 'Then, when I had got as far out as my voice would reach, I began to jeer at the Cyclops.',
    speaker: '', verb: 'target', target: 'cyclops', gateAct: 'jeer',
    gateSfx: 'shout', cue: 'click the Cyclops · jeer at him',
    focus: 'gate-wide', page: 5, beat: 6, set: 'sea', clear: true, bed: 'sea',
    act: 'establish' },

  /* 6.2 — fires on gate 1 — whip to the stern, arm flung at the cliff; the blinded head
     turns toward the sound.
   */
  { id: 'ody-vi-02-taunt', key: 'taunt',
    text: 'Cyclops… you should have taken better measure of your man before eating up his comrades in your cave. You wretch, eat up your visitors in your own house? You might have known that your sin would find you out, and now Jove and the other gods have punished you.',
    speaker: 'ULYSSES', verb: 'auto', dwell: 6.0, focus: 'stern', page: 5,
    beat: 6, set: 'sea', clear: true, act: 'stern-ulysses' },

  /* 6.3 — ROCK 1's clock (~12 s): tear, arc, splash ahead of the rudder, the wash drives
     the ship BACK, pole-push, oars bite; margin cleared for the arc; wait rock1
     holds the page.
   */
  { id: 'ody-vi-03-rock1', key: 'rock1',
    text: 'He got more and more furious as he heard me, so he tore the top from off a high mountain…',
    speaker: '', verb: 'clock', at: 7.0, wait: 'rock1', focus: 'gate-wide',
    page: 5, beat: 6, set: 'sea', clear: true, sfx: 'rock-tear' },

  /* 6.4 — double distance — headland layer scaled back; THE MEN turn from their oars.
   */
  { id: 'ody-vi-04-twiceasfar', key: 'twiceasfar',
    text: 'When we had got twice as far as we were before, I was for jeering at the Cyclops again, but the men begged and prayed of me to hold my tongue.',
    speaker: '', verb: 'click', focus: 'ship-deck', page: 5, beat: 6,
    set: 'sea', clear: true },

  /* 6.5 — the plea — it stays LIT while gate 2 waits; the next click on the Cyclops is a
     click OVER these words (O.12 mechanism).
   */
  { id: 'ody-vi-05-menbeg', key: 'menbeg',
    text: 'Do not… be mad enough to provoke this savage creature further; he has thrown one rock at us already which drove us back again to the mainland, and we made sure it had been the death of us; if he had then heard any further sound of voices he would have pounded our heads and our ship’s timbers into a jelly with the rugged rocks he would have heaved at us, for he can throw them a long way.',
    speaker: 'THE MEN', verb: 'click', focus: 'ship-deck', page: 5, beat: 6,
    set: 'sea', cameo: 'the-men', cap: 'The Men · six at the oars' },

  /* 6.6 — GATE G6, second resolution — NO clear: the men's plea still stands in the
     margin; the strait lens keeps pleaders and target in one frame, composed
     inside the painting at the doubled distance (F2).
   */
  { id: 'ody-vi-06-defy', key: 'defy',
    text: 'But I would not listen to them, and shouted out to him in my rage',
    speaker: '', verb: 'target', target: 'cyclops', gateAct: 'defy',
    gateSfx: 'shout', cue: 'click the Cyclops · name yourself',
    focus: 'strait', page: 5, beat: 6, set: 'sea' },

  /* 6.7 — O.12 lands — he shakes off the gripping hand and steps onto the stern rail;
     the reader's own RELEASE fires the shout; echo off the cliff.
   */
  { id: 'ody-vi-07-myname', key: 'myname',
    text: 'Cyclops, if any one asks you who it was that put your eye out and spoiled your beauty, say it was the valiant warrior Ulysses, son of Laertes, who lives in Ithaca.',
    speaker: 'ULYSSES', verb: 'release', gateAct: 'shout', gateSfx: 'shout',
    cue: 'press and hold · draw breath — release the name', hold: 0.6,
    focus: 'stern', page: 5, beat: 6, set: 'sea', clear: true,
    act: 'stern-rail', fact: 'O.12' },

  /* 6.8 — push past the ship to the cliff-top close; the groan and half-stagger open the
     unit (c2); the ruined eye toward the sea.
   */
  { id: 'ody-vi-08-prophecy', key: 'prophecy',
    text: 'Alas, alas, then the old prophecy about me is coming true. There was a prophet here, at one time, a man both brave and of great stature, Telemus son of Eurymus, who was an excellent seer, and did all the prophesying for the Cyclopes till he grew old; he told me that all this would happen to me some day, and said I should lose my sight by the hand of Ulysses.',
    speaker: 'POLYPHEMUS', verb: 'click', focus: 'clifftop', page: 5, beat: 6,
    set: 'sea', clear: true, sfx: 'groan', cameo: null },

  /* 6.9 — O.13b — "Neptune and I are father and son" confirms Beat IV's plant; the tone
     turns wheedling.
   */
  { id: 'ody-vi-09-fatherson', key: 'fatherson',
    text: 'I have been all along expecting some one of imposing presence and superhuman strength, whereas he turns out to be a little insignificant weakling, who has managed to blind my eye by taking advantage of me in my drink; come here, then, Ulysses, that I may make you presents to show my hospitality, and urge Neptune to help you forward on your journey—for Neptune and I are father and son. He, if he so will, shall heal me, which no one else neither god nor man can do.',
    speaker: 'POLYPHEMUS', verb: 'click', focus: 'clifftop', page: 5, beat: 6,
    set: 'sea', fact: 'O.13b' },

  /* 6.10 — flat and cold over dead-calm water; stern foreground, cliff figure small and
     dark behind.
   */
  { id: 'ody-vi-10-hades', key: 'hades',
    text: 'I wish I could be as sure of killing you outright and sending you down to the house of Hades, as I am that it will take more than Neptune to cure that eye of yours.',
    speaker: 'ULYSSES', verb: 'click', focus: 'stern', page: 5, beat: 6,
    set: 'sea', clear: true, act: 'stern-ulysses' },

  /* 6.11 — O.14a — both hands to the firmament (cut c3); document-weight frame, sky
     darkened a stop, bed to near-silence.
   */
  { id: 'ody-vi-11-curse', key: 'curse',
    text: 'Hear me, great Neptune; if I am indeed your own true begotten son, grant that Ulysses may never reach his home alive; or if he must get back to his friends at last, let him do so late and in sore plight after losing all his men… let him reach his home in another man’s ship and find trouble in his house.',
    speaker: 'POLYPHEMUS', verb: 'click', focus: 'curse', page: 5, beat: 6,
    set: 'sea', clear: true, act: 'curse', fact: 'O.14a' },

  /* 6.12 — O.14b — ROCK 2 rides this clock as the line's punctuation (c4+c5): the
     near-miss astern and the wash drive them ONWARD; receding-shore engages; wait
     rock2 holds the page.
   */
  { id: 'ody-vi-12-heard', key: 'heard',
    text: 'Thus did he pray, and Neptune heard his prayer.', speaker: '',
    verb: 'clock', at: 1.2, wait: 'rock2', focus: 'strait', page: 5, beat: 6,
    set: 'sea', sfx: 'rock-tear', fact: 'O.14b' },

  /* 6.13 — return segment precedes the unit (c6+c7: beach layer, comrades, flock ashore);
     the great ram at a driftwood altar, smoke straight up — and NO sign; dusk
     time-dip follows (c8).
   */
  { id: 'ody-vi-13-ram', key: 'ram',
    text: 'As for the ram, my companions agreed that I should have it as an extra share; so I sacrificed it on the sea shore, and burned its thigh bones to Jove, who is the lord of all. But he heeded not my sacrifice, and only thought how he might destroy both my ships and my comrades.',
    speaker: '', verb: 'click', seg: 'return-beach', segDur: 8.0,
    segHold: true, focus: 'homeward', page: 5, beat: 6, set: 'sea',
    clear: true, sfx: 'keel' },

  /* 6.14 — dawn; departure pantomime under the ellipsis (c9); the click turns the page to
     the closing card (leaf 6). The moonpath lens follows the ship toward the
     painted moonpath — the frame the closing cover rises over.
   */
  { id: 'ody-vi-14-sailedon', key: 'sailedon',
    text: 'When the child of morning rosy-fingered Dawn appeared, I bade my men on board and loose the hawsers… so we sailed on with sorrow in our hearts, but glad to have escaped death though we had lost our comrades.',
    speaker: '', verb: 'click', dwell: 8.0, endsBeat: true, endsBook: true,
    focus: 'moonpath', page: 5, beat: 6, set: 'sea', clear: true, sfx: 'oars',
    act: 'sea-dawn' },
];

/* ------------------------------------------------------------------ *
 * THE BOOK: six beats, five head units, six leaves, three SETS.
 *   - beat 6 has no head UNIT; its heading rides ody-vi-01-jeer.
 *   - leaves 3 is shared by beats 3 and 4 (no turn between them).
 *   - `cave` is mounted on leaves 2, 3 and 4 in state variants.
 * ------------------------------------------------------------------ */
export const BEATS = [
  { n: 1, num: 'I',   title: 'The Tale Begun', set: 'shore', leaf: 1, units: 13 },
  { n: 2, num: 'II',  title: 'The Cave',       set: 'cave',  leaf: 2, units: 14 },
  { n: 3, num: 'III', title: 'Nobody',         set: 'cave',  leaf: 3, units: 14 },
  { n: 4, num: 'IV',  title: 'The Stake',      set: 'cave',  leaf: 3, units: 13 },
  { n: 5, num: 'V',   title: 'The Rams',       set: 'cave',  leaf: 4, units: 13 },
  { n: 6, num: 'VI',  title: 'The Taunt',      set: 'sea',   leaf: 5, units: 14 },
];

export const beatOf = (u) => BEATS[((u && u.beat) || 1) - 1];

/** The closing card the LAST unit turns the page into. A PAGE, not an
 *  overlay: ody-vi-14-sailedon's completing click runs the same cover turn
 *  a page change always ran, and the cover lifts on a page with no picture. */
export const END_PAGE = 6;
export const END_CARD = {
  page: END_PAGE,
  kicker: 'END OF BOOK IX',
  title: 'The Cyclops',
  sub: 'told by Ulysses at the court of Alcinous',
  /* AMENDMENT A1 — THE SEEDED DEDICATION (authored, non-Butler): the ask
   * that rises on the settled card, and the line under the seeded sigil
   * (app/sigil.js draws it; main.js appends the reader's name). */
  ask: 'Who read this?',
  belonged: 'This reading belonged to',
  /* AMENDMENT A2 — HESITATION MEMORY (authored, non-Butler): at `defy`, the
   * reader's second click on the Cyclops, main.js times the pause from the
   * gate arming to the resolving click and the sub gains ONE clause by the
   * 4 s threshold. The base sub above is untouched. */
  subEager: ' — he gave the monster his name at once',
  subHeld: ' — he held his name as long as he could',
};

/** Verb default affordance labels (a unit's own `cue` wins). */
export const CUE_DEFAULT = {
  click:  'click to read on',
  hold:   'press and hold',
  release: 'press and hold · release',
  auto:   '',
  target: 'click the highlighted thing',
  clock:  '',
};

/** The first-visit affordance hint, faded out after the reader's first click. */
export const FIRST_HINT = 'click anywhere to read on';

/** Every leaf the book turns through — the units' pages, then the card's. */
export const PAGES = [...new Set([...UNITS.map(u => u.page), END_PAGE])];

/** The SET a leaf is mounted on. Cave carries leaves 2, 3 and 4. */
export const SET_OF_PAGE = (() => {
  const m = {};
  for (const u of UNITS) m[u.page] = u.set || 'shore';
  m[END_PAGE] = m[END_PAGE] || null;          // the closing card has no picture
  return m;
})();

/** Resolve a unit by CONTENT-odyssey.md key or by full id. */
export function unitByKey(k) {
  return UNITS.find(u => u.key === k || u.id === k) || null;
}

/** The ledger's gate targets, per SET (G1 ship · G2 sword · G5 ram-great ·
 *  G6 cyclops ×2; G3 and G4 are hold gates, not targets). */
export const TARGETS_BY_SET = {
  shore: ['ship'],
  cave:  ['sword', 'ram-great'],
  sea:   ['cyclops'],
};

/** Cheap shape check — the harness asserts this returns []. */
export function validateUnits(units = UNITS) {
  const bad = [];
  const seen = new Set();
  const seenKeys = new Set();
  const VERBS = new Set(['click', 'hold', 'release', 'auto', 'target', 'clock']);
  const ALL_TARGETS = new Set(Object.values(TARGETS_BY_SET).flat());
  const SETS = new Set(Object.keys(TARGETS_BY_SET));
  units.forEach((u, i) => {
    const at = `#${i} ${u.id || '(no id)'}`;
    const set = u.set || 'shore';
    if (!u.id) bad.push(`${at}: missing id`);
    if (seen.has(u.id)) bad.push(`${at}: duplicate id`);
    seen.add(u.id);
    if (!u.key) bad.push(`${at}: missing key (CONTENT-odyssey.md id)`);
    if (seenKeys.has(u.key)) bad.push(`${at}: duplicate key`);
    seenKeys.add(u.key);
    if (typeof u.text !== 'string') bad.push(`${at}: text must be a string`);
    if (!VERBS.has(u.verb)) bad.push(`${at}: verb must be one of ${[...VERBS].join('|')}`);
    if (!u.focus) bad.push(`${at}: missing focus`);
    if (!(u.page >= 1)) bad.push(`${at}: page must be >= 1`);
    if (!SETS.has(set)) bad.push(`${at}: unknown set '${set}'`);
    if (u.verb === 'auto' && !(u.dwell > 0)) bad.push(`${at}: auto needs dwell`);
    if (u.verb === 'hold' && !(u.hold > 0)) bad.push(`${at}: hold needs hold seconds`);
    if (u.verb === 'release' && !(u.hold > 0)) {
      bad.push(`${at}: release needs its hold threshold seconds`);
    }
    if (u.rest && u.verb !== 'hold') bad.push(`${at}: rest rides the hold verb only`);
    if (u.verb === 'clock' && !(u.at > 0)) bad.push(`${at}: clock needs its t+ offset`);
    if (u.verb === 'target' && !ALL_TARGETS.has(u.target)) {
      bad.push(`${at}: target verb needs target in {${[...ALL_TARGETS].join(',')}}`);
    }
    /* A gate must be reachable ON THE SET IT IS PLAYED ON. */
    if (u.verb === 'target' && u.target &&
        !(TARGETS_BY_SET[set] || []).includes(u.target)) {
      bad.push(`${at}: gate '${u.target}' is not a target of SET '${set}'`);
    }
    if (u.verb === 'target' && !u.cue) bad.push(`${at}: target gate needs an explicit cue`);
    if (u.cameo && !u.cap) bad.push(`${at}: cameo needs a caption`);
    if (i > 0 && u.page < units[i - 1].page) bad.push(`${at}: page went backwards`);
    if (i > 0 && u.page !== units[i - 1].page && (u.set || 'shore') === units[i - 1].set &&
        u.beat === units[i - 1].beat) {
      bad.push(`${at}: a page turn inside one beat`);
    }
    // a leaf carries exactly one SET, or the turn has nothing to swap
    const first = units.find((v) => v.page === u.page);
    if ((first.set || 'shore') !== set) {
      bad.push(`${at}: leaf ${u.page} carries two SETs (${first.set} and ${set})`);
    }
  });
  const WANT = 81;
  if (units.length !== WANT) {
    bad.push(`unit count is ${units.length}, the book is ${WANT} ` +
             `(CONTENT-odyssey.md: 76 text units + 5 heads)`);
  }
  for (const b of BEATS) {
    const n = units.filter((u) => ((u.beat || 1) === b.n)).length;
    if (n !== b.units) bad.push(`beat ${b.n} has ${n} units, the ledger says ${b.units}`);
  }
  return bad;
}

